# Generated by Django 4.2.13 on 2026-03-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('sms_type', models.CharField(choices=[('confirmation', 'Booking Confirmation'), ('reminder', '3-Day Reminder'), ('day_of', 'Day-of Reminder'), ('update', 'Event Update'), ('organizer', 'Organizer Notice'), ('general', 'General')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
