# Generated by Django 4.2.13 on 2026-04-26 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_event_city_tickettier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='tickettier',
            options={'ordering': ['category']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tickettier',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='tickettier',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tickettier',
            name='tier_type',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='available',
            field=models.PositiveIntegerField(default=50, help_text='Remaining tickets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettier',
            name='category',
            field=models.CharField(choices=[('early_bird', 'Early Bird'), ('regular', 'Regular'), ('vip', 'VIP'), ('vvip', 'VVIP')], default='regular', help_text='Predefined category determining tier level and UI styling', max_length=20),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='perks',
            field=models.JSONField(blank=True, default=list, help_text='List of perk strings, e.g. ["Front-row seating", "VIP lounge access"]'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='quantity',
            field=models.PositiveIntegerField(default=50, help_text='Total tickets in this tier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettier',
            name='sale_ends',
            field=models.DateTimeField(blank=True, help_text='If set, tier is unavailable after this datetime (useful for Early Bird)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='description',
            field=models.TextField(blank=True, help_text='Short tagline for this tier'),
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
