# Generated by Django 4.2.13 on 2026-04-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_organizer',
        ),
        migrations.AddField(
            model_name='user',
            name='org_description',
            field=models.TextField(blank=True, help_text='Short bio shown on the organizer public profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='org_logo',
            field=models.CharField(blank=True, help_text='URL to organizer logo/banner image', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='org_name',
            field=models.CharField(blank=True, help_text='Display name shown publicly (e.g. TechKenya Events)', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='org_website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
