# Generated by Django 4.2.13 on 2026-04-26 07:01

import bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_booking_booking_code_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='attendee_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='attendee_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='attendee_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='confirmation_sms_sent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='day_of_sms_sent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='mpesa_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='mpesa_verified',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='paypal_verified',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reminder_sms_sent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default=bookings.models.generate_booking_code, help_text='Unique code for digital ticket and venue check-in', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
